"""Versioned run manifest and report contract, and the renderer that reads it."""

from .contract import (
    REPORT_CONTRACT_VERSION,
    RESULT_BASES,
    RESULT_KINDS,
    STANDING_EXCLUSIONS,
    ReportContractError,
    ResultKind,
    RunManifest,
    build_run_manifest,
    read_run_manifest,
    write_run_manifest,
)
from .render import (
    BASIS_HEADING,
    BASIS_WORDING,
    COMPOSITION_SECTIONS,
    DECLARATION_CHECKLIST,
    INDEX_RULE,
    REPORT_RENDER_VERSION,
    SCENARIO_PROVENANCE_ROWS,
    DeclarationRequirement,
    RenderedFigure,
    RenderedReport,
    ReportRenderError,
    render_report,
    write_report,
)

__all__ = [
    "BASIS_HEADING",
    "BASIS_WORDING",
    "COMPOSITION_SECTIONS",
    "DECLARATION_CHECKLIST",
    "INDEX_RULE",
    "REPORT_CONTRACT_VERSION",
    "REPORT_RENDER_VERSION",
    "RESULT_BASES",
    "RESULT_KINDS",
    "SCENARIO_PROVENANCE_ROWS",
    "STANDING_EXCLUSIONS",
    "DeclarationRequirement",
    "RenderedFigure",
    "RenderedReport",
    "ReportContractError",
    "ReportRenderError",
    "ResultKind",
    "RunManifest",
    "build_run_manifest",
    "read_run_manifest",
    "render_report",
    "write_report",
    "write_run_manifest",
]
